spring:
  application:
    name: dds-light

  datasource:
    url: jdbc:postgresql://localhost:5431/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa:
      database-plataform: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true

    flyway:
      enabled: true